name: Build GLPI Agent Installer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.32'

      - name: Install Build Tools
        run: |
          choco install wixtoolset --yes
          cpan install PAR::Packer
          cpan install Wx::Perl::Packager

      - name: Build GLPI Agent Installer
        run: |
          perl Makefile.PL
          dmake
          pp -o glpi-agent.exe script/glpi-agent.pl

      - name: Package as MSI (optional)
        run: |
          candle glpi-agent.wxs
          light -out glpi-agent.msi glpi-agent.wixobj

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: glpi-agent-installer
          path: |
            glpi-agent.exe
            glpi-agent.msi
